# Generated by Django 3.1.5 on 2021-01-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='sampleImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
