# Generated by Django 3.1.5 on 2021-01-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210110_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sampleImage',
            field=models.ImageField(blank=True, default='static/images/640x360Sample.png', null=True, upload_to=''),
        ),
    ]
