# Generated by Django 3.1.5 on 2021-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20210110_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sampleImage',
            field=models.ImageField(blank=True, null=True, upload_to='sample_images'),
        ),
    ]
